### ISSUE TITLE
Download script - tests & documentation

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI-522_City_of_A-Stars_310#18]
**Important**

- Add at least one test or assertion
- Documentation should include URL used for the project so it's easy to run - good place to include this is as a useage example.

**Consider**

- Also, noticing that the resulting "csv" is semicolon separated... not ideal but can work around it if well documented.
- Might be a good idea to also clarify that the output is a folder not a single file - this should be expected based on how zip files work but spelling it out doesn't hurt!

**Comment by manu2856** [comment]
Tests were added to the new scripts as recommended.
