### ISSUE TITLE
Communications/process feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI-522_City_of_A-Stars_310#19]
- **Main issue to improve:** many commits are uninformative eg "proposal updated"  - what part? "fixed document" - which document?
  - Commits linked to issues is great, though! Do more of that!
- Good job tagging and assigning issues - recommend discussion in issues as well. 
- Recommend Code of Conduct contain explicit statement on diversity/inclusion

**Comment by manu2856** [comment]
Thanks for the feedback Kate, we addresses this comments in the release for milestone 2.
